name: Teddy Cloud
version: 0.4.3
slug: teddycloud
description: Alternative server for your Toniebox, allowing you to host the cloud services locally
url: https://github.com/toniebox-reverse-engineering/teddycloud
codenotary: claudio@barto.li
init: false
hassio_api: true
hassio_role: homeassistant
arch:
- aarch64
- amd64
- armv7
map:
- addon_config:rw
image: ghcr.io/toniebox-reverse-engineering/teddycloud/{arch}
options:
  log_level: 'info'
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
# Ingress settings
ingress: true
ingress_port: 0
panel_icon: 'mdi:chip'